sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

scripts: 
  - docker run -e CI=true react-test npm test

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password=stdin
  - docker build -t dumpdacode/multi-client ./client
  - docker push  dumpdacode/multi-client
  - docker build -t dumpdacode/multi-nginx ./nginx
  - docker push  dumpdacode/multi-nginx
  - docker build -t dumpdacode/multi-server ./server
  - docker push  dumpdacode/multi-server
  - docker build -t dumpdacode/multi-worker ./worker
  - docker push  dumpdacode/multi-worker

