sudo: required

services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true react-test npm test

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t dumpdacode/multi-client ./client
  - docker push  dumpdacode/multi-client
  - docker build -t dumpdacode/multi-nginx ./nginx
  - docker push  dumpdacode/multi-nginx
  - docker build -t dumpdacode/multi-server ./server
  - docker push  dumpdacode/multi-server
  - docker build -t dumpdacode/multi-worker ./worker
  - docker push  dumpdacode/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-889019770946'
  bukcet_path: 'multi-docker'
  on: 
    branch: main
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY